services:
  cdk-apt-gpt:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .aws_credentials
    volumes:
      - .:/opt/app
