on: workflow_dispatch
jobs:
  push-to-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - shell: bash
        name: Update Environment
        run: |
          sudo apt update && sudo apt install nodejs
          npm install
      - shell: bash
        name: Build Frontend
        run: |
          pushd frontend/app
          yarn
          yarn build
          rm -rf ../../react-app/build
          cp -r build ../../react-app/
          popd
        env:
          CI: false
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      - shell: bash
        name: Deploy
        run: |
          npx cdk deploy -v --all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretKey }}
          AWS_DEFAULT_REGION: us-east-2
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          AUTH0_DOMAIN: dev-svptkuh71ya7uog8.us.auth0.com
          AUTH0_AUDIENCE: https://dev-svptkuh71ya7uog8.us.auth0.com/api/v2/
          AUTH0_JWKS_URI: https://dev-svptkuh71ya7uog8.us.auth0.com/.well-known/jwks.json
          DB_USER: tilly0315
          DB_HOST: database-2.c1ywou6es1fj.us-east-2.rds.amazonaws.com
          DB_PORT: 5432
          DB_DATABASE: postgres
          DB_PW: ${{ secrets.DB_PW }}
          DB_SSL: true
          FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
          OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OUTSCRAPER_API_KEY: ${{ secrets.OUTSCRAPER_API_KEY }}
          AUTH0_TOKEN_ISSUER: ""

