on: workflow_dispatch
jobs:
  push-to-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - shell: bash
        name: Update Environment
        run: |
          sudo apt update && sudo apt install nodejs
          npm install
      - shell: bash
        name: Deploy
        run: |
          echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_DEFAULT_REGION
          npx cdk deploy --profile jasongauci -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          AWS_PROFILE: jasongauci
